# Generated by Django 5.2.7 on 2025-10-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclappy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type_vehicule_demande',
            field=models.CharField(choices=[('climatiser', 'Climatiser'), ('economique', 'Economique'), ('vip', 'VIP'), ('moto', 'Moto')], default='23:09', max_length=15, verbose_name='Type de véhicule demandé'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarif',
            name='type_vehicule',
            field=models.CharField(choices=[('climatiser', 'Climatiser'), ('economique', 'Economique'), ('vip', 'VIP'), ('moto', 'Moto')], max_length=15, verbose_name='Type de véhicule'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.CharField(choices=[('climatiser', 'Climatiser'), ('economique', 'Economique'), ('vip', 'VIP'), ('moto', 'Moto')], default='berline', max_length=15, verbose_name='Type de véhicule'),
        ),
    ]
