# Generated by Django 5.1.6 on 2025-10-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclappy', '0002_course_type_vehicule_demande_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chauffeur',
            options={'ordering': ['id'], 'verbose_name': 'Chauffeur', 'verbose_name_plural': 'Chauffeurs'},
        ),
        migrations.AlterField(
            model_name='course',
            name='latitude_depart',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True, verbose_name='Latitude départ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='latitude_destination',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True, verbose_name='Latitude destination'),
        ),
        migrations.AlterField(
            model_name='course',
            name='longitude_depart',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True, verbose_name='Longitude départ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='longitude_destination',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True, verbose_name='Longitude destination'),
        ),
    ]
