# Generated by Django 5.1 on 2025-11-08 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclappy', '0003_alter_chauffeur_options_alter_course_latitude_depart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_reservation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de réservation'),
        ),
    ]
