# Generated by Django 5.1 on 2025-11-11 00:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclappy', '0004_alter_course_date_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_reservation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
